package com.lcxs.model.base;

public class userBankBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_bank.id
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_bank.vid
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    private Long vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_bank.bid
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    private Long bid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_bank.id
     *
     * @return the value of c_user_bank.id
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_bank.id
     *
     * @param id the value for c_user_bank.id
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_bank.vid
     *
     * @return the value of c_user_bank.vid
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    public Long getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_bank.vid
     *
     * @param vid the value for c_user_bank.vid
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    public void setVid(Long vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_bank.bid
     *
     * @return the value of c_user_bank.bid
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    public Long getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_bank.bid
     *
     * @param bid the value for c_user_bank.bid
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    public void setBid(Long bid) {
        this.bid = bid;
    }
}