package com.lcxs.mapper.finance;

import com.lcxs.model.finance.priceBean;

public interface priceBeanMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Thu Mar 22 16:38:13 CST 2018
     */
    /* 插入回单拿货价格
     */
    int insert(priceBean price);

    /*查询回单拿货价格
     */
    priceBean selectByRid(long rid);
}