package com.lcxs.mapper.finance;

import java.util.List;

import com.lcxs.model.finance.receiptBean;
import com.lcxs.utils.BaseConditionVO;

public interface receiptBeanMapper {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_receipt
     *
     * @mbggenerated Tue Mar 06 15:48:12 CST 2018
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_receipt
     *
     * @mbggenerated Tue Mar 06 15:48:12 CST 2018
     */
    int insert(receiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_receipt
     *
     * @mbggenerated Tue Mar 06 15:48:12 CST 2018
     */
    int insertSelective(receiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_receipt
     *
     * @mbggenerated Tue Mar 06 15:48:12 CST 2018
     */
    receiptBean selectByRid(Long rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_receipt
     *
     * @mbggenerated Tue Mar 06 15:48:12 CST 2018
     */
    int updateByPrimaryKeySelective(receiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_receipt
     *
     * @mbggenerated Tue Mar 06 15:48:12 CST 2018
     */
    int updateByPrimaryKey(receiptBean record);
    /**
     * 查询所有回单
     */
    List<receiptBean> queryAll(BaseConditionVO vo);
    /**
     * 根据传入的时候查询这个时段的回单
     * @param vo keywrodsname=开始时间  keywordsnumber=结束时间 keywordsstaus=状态
     * @return
     */
    List<receiptBean> queryAnyDayOfReceipt(BaseConditionVO vo);
    /**
     * 查询今日打款人
     * @param vo
     * @return
     */
    List<receiptBean> queryToDayMoneyPerson(BaseConditionVO vo);
    /**
     * 查询今日打款金额
     * @param vo
     * @return
     */
    Double queryToDayMoney();
    /**
     * 根据vid查询有几单是通过的或打款的
     */
    Object queryReceiptNumByVid(Long vid);


}