package com.lcxs.mapper.finance;

import java.util.List;

import com.lcxs.model.finance.TsBean;
import com.lcxs.model.finance.receiptBean;
import com.lcxs.utils.BaseConditionVO;

public interface TsBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_ts
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_ts
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    int insert(TsBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_ts
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    int insertSelective(TsBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_ts
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    TsBean selectByPrimaryKey(Long vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_ts
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    int updateByPrimaryKeySelective(TsBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_ts
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    int updateByPrimaryKey(TsBean record);
    List<TsBean> queryAll(BaseConditionVO vo);
    /**
     * 根据vid查询邀请人数
     */
    Object queryTsNumByVid(Long vid);
    int updatePassMoney(String  tsid);
}