package com.lcxs.mapper.finance;

import java.util.List;

import com.lcxs.model.base.userBean;
import com.lcxs.model.finance.UserReceiptBean;
import com.lcxs.model.homepage.homeBean;
import com.lcxs.utils.BaseConditionVO;
import com.lcxs.model.finance.receiptBean;
public interface UserReceiptBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    int insert(UserReceiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    int insertSelective(UserReceiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    UserReceiptBean selectByRid(Long rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    int updateByPrimaryKeySelective(UserReceiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    int updateByPrimaryKey(UserReceiptBean record);
    /**
     * 平台数据
     * @return
     */
    List<homeBean> queryShopData(BaseConditionVO vo);
    /**
     * 活动数据
     * @return
     */
    List<homeBean> queryActivityData(BaseConditionVO vo);
    /**
     * 根据回单rid查找用户
     */
    userBean queryUserByRid(Long rid);
    /**
     * 根据用户vid查询用户回单已打款的数量
     */
    Object queryReceiptNumByVid(Long vid);
    /**
     * 根据用户invitation查询所有回单数据
     */
    List<receiptBean> queryReceiptData(BaseConditionVO vo);

}