package com.lcxs.service.finance;

import com.github.pagehelper.PageInfo;
import com.lcxs.model.finance.UserReceiptBean;

import com.lcxs.model.finance.receiptBean;
import com.lcxs.model.homepage.homeBean;
import com.lcxs.utils.BaseConditionVO;
import com.lcxs.model.homepage.homeBean;
import com.lcxs.utils.BaseConditionVO;

public interface IUserReceiptService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    int insert(UserReceiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    int insertSelective(UserReceiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    UserReceiptBean selectByRid(Long rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    int updateByPrimaryKeySelective(UserReceiptBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_receipt
     *
     * @mbggenerated Wed Mar 07 12:35:13 CST 2018
     */
    int updateByPrimaryKey(UserReceiptBean record);

    PageInfo<homeBean>queryActivityData(BaseConditionVO vo);


    /**
     * 平台数据
     * @param vo
     * @return
     */
    
    PageInfo<homeBean> queryShopData(BaseConditionVO vo);

    /**
     * 推手用户数据
     */
    PageInfo<receiptBean> queryReceiptData(BaseConditionVO vo);
}
