package com.lcxs.service.product;


import com.github.pagehelper.PageInfo;
import com.lcxs.model.product.channelBean;
import com.lcxs.utils.BaseConditionVO;

public interface IChannelService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_channel
     *
     * @mbggenerated Sat Mar 10 10:11:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_channel
     *
     * @mbggenerated Sat Mar 10 10:11:11 CST 2018
     */
    int insert(channelBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_channel
     *
     * @mbggenerated Sat Mar 10 10:11:11 CST 2018
     */
    int insertSelective(channelBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_channel
     *
     * @mbggenerated Sat Mar 10 10:11:11 CST 2018
     */
    channelBean selectByCid(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_channel
     *
     * @mbggenerated Sat Mar 10 10:11:11 CST 2018
     */
    int updateByPrimaryKeySelective(channelBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_channel
     *
     * @mbggenerated Sat Mar 10 10:11:11 CST 2018
     */
    int updateByPrimaryKey(channelBean record);
    /**
     * 查询所有渠道
     */
    PageInfo<channelBean> queryAll(BaseConditionVO vo);
    /**
     * 删除渠道信息
     * @param id
     * @return
     */
    Long deleteById(Long id);
}
