package com.lcxs.model.product;

public class bannerBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_banner.id
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_banner.title
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_banner.picture
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_banner.link
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_banner.status
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_banner.sort
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_banner.type
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_banner.id
     *
     * @return the value of c_banner.id
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_banner.id
     *
     * @param id the value for c_banner.id
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_banner.title
     *
     * @return the value of c_banner.title
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_banner.title
     *
     * @param title the value for c_banner.title
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_banner.picture
     *
     * @return the value of c_banner.picture
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_banner.picture
     *
     * @param picture the value for c_banner.picture
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_banner.link
     *
     * @return the value of c_banner.link
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_banner.link
     *
     * @param link the value for c_banner.link
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_banner.status
     *
     * @return the value of c_banner.status
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_banner.status
     *
     * @param status the value for c_banner.status
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_banner.sort
     *
     * @return the value of c_banner.sort
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_banner.sort
     *
     * @param sort the value for c_banner.sort
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_banner.type
     *
     * @return the value of c_banner.type
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_banner.type
     *
     * @param type the value for c_banner.type
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }
}