package com.lcxs.model.product;

public class channelBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_channel.id
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_channel.cid
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_channel.cname
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_channel.realname
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_channel.phone
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_channel.qnumber
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    private String qnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_channel.wnumber
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    private String wnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_channel.person
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    private String person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_channel.status
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_channel.qdlj
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    private String qdlj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_channel.ctime
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    private String ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_channel.id
     *
     * @return the value of c_channel.id
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_channel.id
     *
     * @param id the value for c_channel.id
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_channel.cid
     *
     * @return the value of c_channel.cid
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_channel.cid
     *
     * @param cid the value for c_channel.cid
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_channel.cname
     *
     * @return the value of c_channel.cname
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_channel.cname
     *
     * @param cname the value for c_channel.cname
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_channel.realname
     *
     * @return the value of c_channel.realname
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_channel.realname
     *
     * @param realname the value for c_channel.realname
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_channel.phone
     *
     * @return the value of c_channel.phone
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_channel.phone
     *
     * @param phone the value for c_channel.phone
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_channel.qnumber
     *
     * @return the value of c_channel.qnumber
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public String getQnumber() {
        return qnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_channel.qnumber
     *
     * @param qnumber the value for c_channel.qnumber
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public void setQnumber(String qnumber) {
        this.qnumber = qnumber == null ? null : qnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_channel.wnumber
     *
     * @return the value of c_channel.wnumber
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public String getWnumber() {
        return wnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_channel.wnumber
     *
     * @param wnumber the value for c_channel.wnumber
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public void setWnumber(String wnumber) {
        this.wnumber = wnumber == null ? null : wnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_channel.person
     *
     * @return the value of c_channel.person
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_channel.person
     *
     * @param person the value for c_channel.person
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_channel.status
     *
     * @return the value of c_channel.status
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_channel.status
     *
     * @param status the value for c_channel.status
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_channel.qdlj
     *
     * @return the value of c_channel.qdlj
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public String getQdlj() {
        return qdlj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_channel.qdlj
     *
     * @param qdlj the value for c_channel.qdlj
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public void setQdlj(String qdlj) {
        this.qdlj = qdlj == null ? null : qdlj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_channel.ctime
     *
     * @return the value of c_channel.ctime
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_channel.ctime
     *
     * @param ctime the value for c_channel.ctime
     *
     * @mbggenerated Sat Mar 10 14:49:35 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }
}