package com.lcxs.model.product;

public class noteBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_note.id
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_note.title
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_note.ctime
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_note.status
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_note.type
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_note.content
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_note.id
     *
     * @return the value of c_note.id
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_note.id
     *
     * @param id the value for c_note.id
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_note.title
     *
     * @return the value of c_note.title
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_note.title
     *
     * @param title the value for c_note.title
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_note.ctime
     *
     * @return the value of c_note.ctime
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_note.ctime
     *
     * @param ctime the value for c_note.ctime
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_note.status
     *
     * @return the value of c_note.status
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_note.status
     *
     * @param status the value for c_note.status
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_note.type
     *
     * @return the value of c_note.type
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_note.type
     *
     * @param type the value for c_note.type
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_note.content
     *
     * @return the value of c_note.content
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_note.content
     *
     * @param content the value for c_note.content
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}