package com.lcxs.model.product;

public class upBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_shop_update.id
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_shop_update.shopid
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    private Long shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_shop_update.shopname
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    private String shopname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_shop_update.oldchannel
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    private String oldchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_shop_update.xchannel
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    private String xchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_shop_update.oldshopurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    private String oldshopurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_shop_update.xshopurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    private String xshopurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_shop_update.oldappurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    private String oldappurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_shop_update.xappurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    private String xappurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_shop_update.ctime
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    private String ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_shop_update.id
     *
     * @return the value of c_shop_update.id
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_shop_update.id
     *
     * @param id the value for c_shop_update.id
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_shop_update.shopid
     *
     * @return the value of c_shop_update.shopid
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public Long getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_shop_update.shopid
     *
     * @param shopid the value for c_shop_update.shopid
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public void setShopid(Long shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_shop_update.shopname
     *
     * @return the value of c_shop_update.shopname
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_shop_update.shopname
     *
     * @param shopname the value for c_shop_update.shopname
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_shop_update.oldchannel
     *
     * @return the value of c_shop_update.oldchannel
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public String getOldchannel() {
        return oldchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_shop_update.oldchannel
     *
     * @param oldchannel the value for c_shop_update.oldchannel
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public void setOldchannel(String oldchannel) {
        this.oldchannel = oldchannel == null ? null : oldchannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_shop_update.xchannel
     *
     * @return the value of c_shop_update.xchannel
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public String getXchannel() {
        return xchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_shop_update.xchannel
     *
     * @param xchannel the value for c_shop_update.xchannel
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public void setXchannel(String xchannel) {
        this.xchannel = xchannel == null ? null : xchannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_shop_update.oldshopurl
     *
     * @return the value of c_shop_update.oldshopurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public String getOldshopurl() {
        return oldshopurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_shop_update.oldshopurl
     *
     * @param oldshopurl the value for c_shop_update.oldshopurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public void setOldshopurl(String oldshopurl) {
        this.oldshopurl = oldshopurl == null ? null : oldshopurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_shop_update.xshopurl
     *
     * @return the value of c_shop_update.xshopurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public String getXshopurl() {
        return xshopurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_shop_update.xshopurl
     *
     * @param xshopurl the value for c_shop_update.xshopurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public void setXshopurl(String xshopurl) {
        this.xshopurl = xshopurl == null ? null : xshopurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_shop_update.oldappurl
     *
     * @return the value of c_shop_update.oldappurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public String getOldappurl() {
        return oldappurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_shop_update.oldappurl
     *
     * @param oldappurl the value for c_shop_update.oldappurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public void setOldappurl(String oldappurl) {
        this.oldappurl = oldappurl == null ? null : oldappurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_shop_update.xappurl
     *
     * @return the value of c_shop_update.xappurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public String getXappurl() {
        return xappurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_shop_update.xappurl
     *
     * @param xappurl the value for c_shop_update.xappurl
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public void setXappurl(String xappurl) {
        this.xappurl = xappurl == null ? null : xappurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_shop_update.ctime
     *
     * @return the value of c_shop_update.ctime
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_shop_update.ctime
     *
     * @param ctime the value for c_shop_update.ctime
     *
     * @mbggenerated Thu Apr 19 17:52:50 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }
}