package com.lcxs.mapper.product;

import java.util.List;

import com.lcxs.model.product.bannerBean;
import com.lcxs.utils.BaseConditionVO;

public interface bannerBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_banner
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_banner
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    int insert(bannerBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_banner
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    int insertSelective(bannerBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_banner
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    bannerBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_banner
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    int updateByPrimaryKeySelective(bannerBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_banner
     *
     * @mbggenerated Thu Mar 15 16:53:54 CST 2018
     */
    int updateByPrimaryKey(bannerBean record);
    
    /**
     * 查询横幅全部信息
     * @param vo
     * @return
     */
    
    List<bannerBean> findAll(BaseConditionVO vo);
    /**
     * 删除商户信息
     * @param id
     * @return
     */
    int deleteByid(int id);
}