package com.lcxs.mapper.product;

import java.util.List;

import com.lcxs.model.product.caseBean;
import com.lcxs.utils.BaseConditionVO;

public interface caseBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_case
     *
     * @mbggenerated Fri Mar 09 15:46:20 CST 2018
     */
    int deleteByid(Long id);
    int upByid(Long id);

   /**
    * 添加方案信息
    * @param record
    * @return
    */
    int insert(caseBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_case
     *
     * @mbggenerated Fri Mar 09 15:46:20 CST 2018
     */
    int insertSelective(caseBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_case
     *
     * @mbggenerated Fri Mar 09 15:46:20 CST 2018
     */
    caseBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_case
     *
     * @mbggenerated Fri Mar 09 15:46:20 CST 2018
     */
    int updateByPrimaryKeySelective(caseBean record);

   /**
    * 修改方案
    * @param record
    * @return
    */
    int updateByPrimaryKey(caseBean record);
    
    /**
     * 根据产品id查找全部方案
     */
    List<caseBean> findById(BaseConditionVO vo);
    /**
     * 根据产品名称和方案id查找方案
     */
    caseBean selectCaseByProjectAndCid(BaseConditionVO vo);
    /**
     * 根据产品id查找全部方案
     */
    List<caseBean> findOldById(BaseConditionVO vo);
    int deleteBypid(Long productid);
    int upBypid(Long productid);
    
}