package com.lcxs.mapper.product;

import java.util.List;

import com.lcxs.model.product.channelBean;
import com.lcxs.utils.BaseConditionVO;

public interface channelBeanMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_channel
	 * @mbggenerated  Sat Mar 10 13:28:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * 添加渠道信息
	 * @param record
	 * @return
	 */
	int insert(channelBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_channel
	 * @mbggenerated  Sat Mar 10 13:28:56 CST 2018
	 */
	int insertSelective(channelBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_channel
	 * @mbggenerated  Sat Mar 10 13:28:56 CST 2018
	 */
	channelBean selectByCid(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_channel
	 * @mbggenerated  Sat Mar 10 13:28:56 CST 2018
	 */
	int updateByPrimaryKeySelective(channelBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table c_channel
	 * @mbggenerated  Sat Mar 10 13:28:56 CST 2018
	 */
	int updateByPrimaryKey(channelBean record);

	/**
     * 查询全部渠道信息
     */
    List<channelBean> queryAll(BaseConditionVO vo);
    /**
     * 删除渠道信息
     * @param id
     * @return
     */
    Long deleteById(Long id);
    
    /**
     * 修改渠道信息
     * @param record
     * @return
     */
   channelBean updateShop(channelBean c);

}