package com.lcxs.mapper.product;

import java.util.List;

import com.lcxs.model.product.noteBean;
import com.lcxs.utils.BaseConditionVO;

public interface noteBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    int insert(noteBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    int insertSelective(noteBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    noteBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    int updateByPrimaryKeySelective(noteBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(noteBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_note
     *
     * @mbggenerated Thu Mar 15 16:57:19 CST 2018
     */
    int updateByPrimaryKey(noteBean record);
    List<noteBean> findAllNote(BaseConditionVO vo);//查询所有公告
    int deleteById(Integer id);//根据id冻结公告
}