package com.lcxs.mapper.product;

import java.util.List;

import com.lcxs.model.product.productBean;
import com.lcxs.utils.BaseConditionVO;

public interface productBeanMapper {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_product
     *
     * @mbggenerated Wed Mar 07 14:06:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

   /**
    * 添加产品信息
    * @param record
    * @return
    */
    int insert(productBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_product
     *
     * @mbggenerated Wed Mar 07 14:06:51 CST 2018
     */
    int insertSelective(productBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_product
     *
     * @mbggenerated Wed Mar 07 14:06:51 CST 2018
     */
    productBean selectByPrimaryKey(Long id);

    /**
     * 修改产品信息
     * @param record
     * @return
     */
    int updateByPrimaryKeySelective(productBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_product
     *
     * @mbggenerated Wed Mar 07 14:06:51 CST 2018
     */
    int updateByPrimaryKey(productBean record);
    int updateByShopid (productBean record);
    /**
     * 根据商户id查询产品全部信息
     * @param vo
     * @return
     */
    
    List<productBean> findByShopid(BaseConditionVO vo);
    
    /**
     * 删除商户信息
     * @param id
     * @return
     */
    Long deleteBypid(Long pid);
    
    /**
     * 根据商户id查询产品历史信息
     * @param vo
     * @return
     */
    
    List<productBean> findOldByShopid(BaseConditionVO vo);
    List<productBean>findAll(BaseConditionVO vo);
    /**
     * 上架商户信息
     * @param pid
     * @return
     */
    Long upBypid(Long pid);
    List<productBean>findOld(BaseConditionVO vo);
}