package com.lcxs.mapper.product;

import java.util.List;

import com.lcxs.model.base.userRedBean;
import com.lcxs.model.product.redBean;
import com.lcxs.utils.BaseConditionVO;

public interface redBeanMapper {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_red
     *
     * @mbggenerated Fri Mar 09 12:45:33 CST 2018
     */
    int deleteByPrimaryKey(Long id);

  /**
   * 添加红包信息
   * @param record
   * @return
   */
    int insert(redBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_red
     *
     * @mbggenerated Fri Mar 09 12:45:33 CST 2018
     */
    int insertSelective(redBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_red
     *
     * @mbggenerated Fri Mar 09 12:45:33 CST 2018
     */
    redBean selectByPrimaryKey(Long id);


    /**
     * 修改红包信息
     * @param record
     * @return
     */
    int updateByPrimaryKeySelective(redBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_red
     *
     * @mbggenerated Fri Mar 09 12:45:33 CST 2018
     */
    int updateByPrimaryKey(redBean record);


    /**
     * 查找全部红包信息
     * @param vo
     * @return
     */
    List<redBean> findAll(BaseConditionVO vo);
    /**
     * 根据编号删除红包信息
     * @param redid
     * @return
     */
    Long deleteByRedid(Long redid);
    List<redBean> findRedName();//查找没过期的红包
    redBean findRedByName(String redname);//根据红包名字查找红包
    Long upByRedid(Long redid);

    //查询全部用户红包
    List<userRedBean> findUserRedAll(BaseConditionVO vo);
}