package com.lcxs.mapper.product;

import java.util.List;

import com.lcxs.model.product.shopBean;
import com.lcxs.utils.BaseConditionVO;

public interface shopBeanMapper {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shop
     *
     * @mbggenerated Mon Mar 05 17:57:37 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 增加商户信息
     * @param shop
     * @return
     */
    int insert(shopBean shop);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shop
     *
     * @mbggenerated Mon Mar 05 17:57:37 CST 2018
     */
    int insertSelective(shopBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shop
     *
     * @mbggenerated Mon Mar 05 17:57:37 CST 2018
     */
    shopBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_shop
     *
     * @mbggenerated Mon Mar 05 17:57:37 CST 2018
     */
    int updateByPrimaryKeySelective(shopBean record);

    
    /**
     * 查询商户全部信息
     * @param vo
     * @return
     */
    
    List<shopBean> findAll(BaseConditionVO vo);
    /**
     * 删除商户信息
     * @param id
     * @return
     */
    Long deleteByShopid(Long shopid);
    /**
     * 查询历史商户信息
     */
    List<shopBean> findOld(BaseConditionVO vo);
    /**
     * 上架商户信息
     * @param pid
     * @return
     */
    Long upByshopid(Long shopid);
}