package com.lcxs.mapper.base;

import com.lcxs.model.base.bankBean;

public interface bankBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Wed Apr 18 11:02:27 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Wed Apr 18 11:02:27 CST 2018
     */
    int insert(bankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Wed Apr 18 11:02:27 CST 2018
     */
    int insertSelective(bankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Wed Apr 18 11:02:27 CST 2018
     */
    bankBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Wed Apr 18 11:02:27 CST 2018
     */
    int updateByPrimaryKeySelective(bankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_bank
     *
     * @mbggenerated Wed Apr 18 11:02:27 CST 2018
     */
    int updateByPrimaryKey(bankBean record);
    /**
     * 根据用户vid查询银行卡信息
     */
    bankBean  queryBankByVid(Long vid);
}