package com.lcxs.mapper.base;

import com.lcxs.model.base.userBankBean;

public interface userBankBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    int insert(userBankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    int insertSelective(userBankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    userBankBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    int updateByPrimaryKeySelective(userBankBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_bank
     *
     * @mbggenerated Wed Apr 18 11:02:48 CST 2018
     */
    int updateByPrimaryKey(userBankBean record);
}