package com.lcxs.mapper.base;

import com.lcxs.model.base.userRedBean;
import com.lcxs.utils.BaseConditionVO;

import java.util.List;

public interface userRedBeanMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_red
     *
     * @mbggenerated Thu Apr 12 16:59:13 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_red
     *
     * @mbggenerated Thu Apr 12 16:59:13 CST 2018
     */
    int insert(userRedBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_red
     *
     * @mbggenerated Thu Apr 12 16:59:13 CST 2018
     */
    int insertSelective(userRedBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_red
     *
     * @mbggenerated Thu Apr 12 16:59:13 CST 2018
     */
    userRedBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_red
     *
     * @mbggenerated Thu Apr 12 16:59:13 CST 2018
     */
    int updateByPrimaryKeySelective(userRedBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_red
     *
     * @mbggenerated Thu Apr 12 16:59:13 CST 2018
     */
    int updateByPrimaryKey(userRedBean record);
    /**
     * 根据回单rid查询红包
     */
    userRedBean queryUserRedByRid(Long rid);

    List<userRedBean> findUserRedAll(BaseConditionVO vo);//显示所有用户信息
}