package com.lcxs.mapper.base;

import java.util.List;



import com.lcxs.model.base.bankBean;
import com.lcxs.model.base.userBean;
import com.lcxs.model.finance.receiptBean;
import com.lcxs.utils.BaseConditionVO;

public interface userBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Mon Mar 05 17:59:52 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Mon Mar 05 17:59:52 CST 2018
     */
    int insert(userBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Mon Mar 05 17:59:52 CST 2018
     */
    int insertSelective(userBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Mon Mar 05 17:59:52 CST 2018
     */
    userBean selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Mon Mar 05 17:59:52 CST 2018
     */
    int updateByPrimaryKeySelective(userBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user
     *
     * @mbggenerated Mon Mar 05 17:59:52 CST 2018
     */
    int updateByPrimaryKey(userBean record);
    List<userBean> findAll(BaseConditionVO vo);//显示所有用户信息
    Object findTotalMoney(Long vid);//查询用户总投资金额
    Object findTotalReturnAmount(Long vid);//查询用户总返现方案金
    Object findTotalRedAmount(Long vid);//查询用户总返现红包金额
    Object findReadyAmount(Long vid);//查询用户已提现金额
    userBean findUserByVid(Long vid);//根据vid查询用户信息
    int deleteUserByVid(Long vid);//根据vid冻结用户
    int updateUserByVid(userBean user);//根据vid修改用户信息
    List<receiptBean> findInvestment(BaseConditionVO vo);//根据vid查找用户投资回单
    List<receiptBean> findReadyInvestment(BaseConditionVO vo);//根据vid查找用户已打款回单
    List<bankBean> findBankByVid(BaseConditionVO vo);//根据vid查找用户绑定的银行卡
    Integer findFriendAll(Long vid);//根据vid查询好友个数
    Integer findBankCount(Long vid);//根据vid查询绑定的银行个数
    List<userBean> findFriendInfo(BaseConditionVO vo);//根据vid查询用户的好友信息
    int deleteBank(Long id);//根据银行账号删除银行
    int deleteBankM(Long bid);//根据bid删除银行中间表信息
    List<userBean> findTodayR(BaseConditionVO vo);//查询今日注册用户信息
    int changePwd(BaseConditionVO vo);//根据用户编号修改密码
    /**
     * 根据用户被邀请码找到邀请人
     */
    userBean queryUserByInvitation(String invitation);
    userBean findUserByRid(Long rid);//根据回单编号查找用户
    userBean findFriend(String invitation);//根据邀请码查找邀请我的人
    List<receiptBean> findReceipt(Long vid);//根据vid查找用户回单
    userBean findUser(Long vid);
    List<userBean> findUserByPhone(String phone);//根据电话号码查找用户
    int updateByPhone(userBean user);//根据电话号码绑定客服
    List<Long> findAllInfo();
    int updateOwnByVid(long vid);//根据vid修改邀请码
    List<userBean> findTsFriendInfo(BaseConditionVO vo);//根据vid查询用户的ts信息
    userBean findTsFriend(String owninvitation);//根据ts邀请码查找邀请我的人
    Integer findTsFriendAll(Long vid);
}