package com.lcxs.model.finance;

public class TsBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_ts.id
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_ts.tsid
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    private String tsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_ts.phone
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    private Long phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_ts.ailpay
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    private String ailpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_ts.realname
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_ts.ljmoney
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    private Double ljmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_ts.dkmoney
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    private Double dkmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_ts.yqren
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    private Integer yqren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_ts.nexttime
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    private String nexttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_ts.id
     *
     * @return the value of c_ts.id
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_ts.id
     *
     * @param id the value for c_ts.id
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_ts.tsid
     *
     * @return the value of c_ts.tsid
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public String getTsid() {
        return tsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_ts.tsid
     *
     * @param tsid the value for c_ts.tsid
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public void setTsid(String tsid) {
        this.tsid = tsid == null ? null : tsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_ts.phone
     *
     * @return the value of c_ts.phone
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public Long getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_ts.phone
     *
     * @param phone the value for c_ts.phone
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_ts.ailpay
     *
     * @return the value of c_ts.ailpay
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public String getAilpay() {
        return ailpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_ts.ailpay
     *
     * @param ailpay the value for c_ts.ailpay
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public void setAilpay(String ailpay) {
        this.ailpay = ailpay == null ? null : ailpay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_ts.realname
     *
     * @return the value of c_ts.realname
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_ts.realname
     *
     * @param realname the value for c_ts.realname
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_ts.ljmoney
     *
     * @return the value of c_ts.ljmoney
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public Double getLjmoney() {
        return ljmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_ts.ljmoney
     *
     * @param ljmoney the value for c_ts.ljmoney
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public void setLjmoney(Double ljmoney) {
        this.ljmoney = ljmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_ts.dkmoney
     *
     * @return the value of c_ts.dkmoney
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public Double getDkmoney() {
        return dkmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_ts.dkmoney
     *
     * @param dkmoney the value for c_ts.dkmoney
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public void setDkmoney(Double dkmoney) {
        this.dkmoney = dkmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_ts.yqren
     *
     * @return the value of c_ts.yqren
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public Integer getYqren() {
        return yqren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_ts.yqren
     *
     * @param yqren the value for c_ts.yqren
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public void setYqren(Integer yqren) {
        this.yqren = yqren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_ts.nexttime
     *
     * @return the value of c_ts.nexttime
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public String getNexttime() {
        return nexttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_ts.nexttime
     *
     * @param nexttime the value for c_ts.nexttime
     *
     * @mbggenerated Thu May 24 12:21:44 CST 2018
     */
    public void setNexttime(String nexttime) {
        this.nexttime = nexttime == null ? null : nexttime.trim();
    }

    // at moument
    @Override
    public String toString() {
        return "TsBean{" +
                "id=" + id +
                ", tsid='" + tsid + '\'' +
                ", phone=" + phone +
                ", ailpay='" + ailpay + '\'' +
                ", realname='" + realname + '\'' +
                ", ljmoney=" + ljmoney +
                ", dkmoney=" + dkmoney +
                ", yqren=" + yqren +
                ", nexttime='" + nexttime + '\'' +
                '}';
    }
}