package com.lcxs.model.finance;

public class UserTsBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_ts.id
     *
     * @mbggenerated Thu May 24 12:26:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_ts.vid
     *
     * @mbggenerated Thu May 24 12:26:20 CST 2018
     */
    private Long vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_ts.tsid
     *
     * @mbggenerated Thu May 24 12:26:20 CST 2018
     */
    private String tsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_ts.id
     *
     * @return the value of c_user_ts.id
     *
     * @mbggenerated Thu May 24 12:26:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_ts.id
     *
     * @param id the value for c_user_ts.id
     *
     * @mbggenerated Thu May 24 12:26:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_ts.vid
     *
     * @return the value of c_user_ts.vid
     *
     * @mbggenerated Thu May 24 12:26:20 CST 2018
     */
    public Long getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_ts.vid
     *
     * @param vid the value for c_user_ts.vid
     *
     * @mbggenerated Thu May 24 12:26:20 CST 2018
     */
    public void setVid(Long vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_ts.tsid
     *
     * @return the value of c_user_ts.tsid
     *
     * @mbggenerated Thu May 24 12:26:20 CST 2018
     */
    public String getTsid() {
        return tsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_ts.tsid
     *
     * @param tsid the value for c_user_ts.tsid
     *
     * @mbggenerated Thu May 24 12:26:20 CST 2018
     */
    public void setTsid(String tsid) {
        this.tsid = tsid == null ? null : tsid.trim();
    }
}